### ISSUE TITLE
I can't get it to work? What am I doing wrong?

### ISSUE THREAD

**Issue by kramer65** [monospaced/angular-qrcode#13]
I'm trying to use angular-qrcode, but I can't seem to get it to work. I tried using it in the angular-phonecat tutorial app here: https://github.com/kramer65/angular-phonecat/commit/6e686f49827c0992378d611bab68517c7bf3b6b0

Unfortunately it doesn't return anything; no qr-code, but also no error. Simply nothing.

Does anybody know what I'm doing wrong? All tips are welcome!

**Comment by roman-mkh** [comment]
Check if you include all js libraries
```html
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
  <script src="//monospaced.github.io/bower-qrcode-generator/js/qrcode.js"></script>
  <script src="//monospaced.github.io/bower-qrcode-generator/js/qrcode_UTF8.js"></script>
  <script src="qrcode.js"></script>
```
Check if you include module dependency to monospaced.qrcode
```javascript
var app = angular.module('MyApp', [ 'monospaced.qrcode' ]);
```

**Comment by monospaced** [comment]
I've renamed `qcode.js` BTW, so now it's 

````
<script src="angular-qrcode.js"></script>
```

Did you manage to get it working?

**Comment by yunap** [comment]
Hi there!

I think I am including all of the right dependancies. I am able to generate a qr code from data="some string". However I get a blank canvas when attempting to generate qr code from url. What am I missing?

<qrcode version="4" error-correction-level="M" size="200" data="otpauth://totp/Peaxy%20Inc:yp@peaxy.net?secret=LJBYNGBDHMRCOZG7&amp;issuer=Peaxy+Inc">
<canvas class="qrcode" height="200" width="200"></canvas>
</qrcode>

**Comment by monospaced** [comment]
Likely the version number is too low, see https://github.com/monospaced/angular-qrcode#options
