### ISSUE TITLE
Cannot print small QR codes in Google Chrome

### ISSUE THREAD

**Issue by idpaterson** [monospaced/angular-qrcode#20]
In a recent update it seems that Google Chrome is no longer printing QR codes that are 256 pixels or less (seen on Chrome 43 Windows and Mac). This problem does not seem to affect [a different `canvas`-based qr code module](https://github.com/janantala/angular-qr). Enabling the `download` option also seems to allow the QR code to print.

To test, open the [demo page](http://monospaced.github.io/angular-qrcode/) in Chrome and print the page. The print preview shows all three QR codes. Next, change the size to 256 and print. Only the downloadable QR code is displayed in the print preview.

This seems to be caused by a recent browser update and does not affect other browsers as far as I can tell. However, hopefully there is something you can think of that might fix it!

![QR codes](https://cloud.githubusercontent.com/assets/507058/8044680/32a146fe-0dfc-11e5-916b-1f5107fefc9e.png)

**Comment by monospaced** [comment]
Hi,

I actually can't recreate this issue. 

Following your steps in Chrome 43.0.2357.134 on Mac, I can see the OR codes in the preview:

![screen shot 2015-07-17 at 17 02 49](https://cloud.githubusercontent.com/assets/98794/8751657/517df87e-2ca6-11e5-93e4-64dff474d8d2.png)

**Comment by idpaterson** [comment]
Agreed, it seems to have been resolved.

**Comment by monospaced** [comment]
Yay!

**Comment by kimsean** [comment]
hi what module did you use to print for the code. I cant see any in print preview no matter any size. i use the ngPrint

**Comment by idpaterson** [comment]
No module, just the browser's print function. Please consider opening an issue here or on ngPrint if there are problems with your specific setup.
