### ISSUE TITLE
download not working in IE(11)

### ISSUE THREAD

**Issue by tsquare76** [monospaced/angular-qrcode#21]
Hi,

I'm looking into using this directive to generate downloadable qr codes for my users, unfortunately the vast majority of these users are using Internet Explorer, and are not allowed to install / use anything else so I need a solution that works on IE.

I have tested the demo page for this project, and it does not seem to work with IE (I've tried with version 11) - is there a way to get it working for IE. (not eaven right clicking on the qr code works, as IE does not seem to see canvas as an image it can save...)

I have got the qr-code generation working on my site, but download does not work at all, not even on Chrome or FireFox, but I'll keep investigating that if I can get IE to work cause that's the main concern.

**Comment by monospaced** [comment]
download attribute is not supported in IE

canvas elements are _not_ images that you can save

so, if you need IE support + download support, you could force the directive to always use the image fallback option, which is intended for browser (like old IE) that don't support canvas

setting `canvas2D` to `false` will do the trick, you could implement your own 'if IE' test to add as an OR condition to this assignment:

```
canvas2D = !!$window.CanvasRenderingContext2D,
````

**Comment by tsquare76** [comment]
Thanks for the reply, I have made a locally modified version that allows for "Save image as...".
