### ISSUE TITLE
download not work on ionic

### ISSUE THREAD

**Issue by donnygunawan93** [monospaced/angular-qrcode#33]
I use this with ionic and i found download not work, any one can help? thx ^_^

**Comment by qybksbb** [comment]
i have the same question. download can work on chrome, but doesn't wokr on my app on android.

**Comment by jedmarcnocum** [comment]
Same here. Hope someone can provide a way to download the image.

**Comment by monospaced** [comment]
This is most likely due to lack of support for the `download` attribute in the affected browsers.

See http://caniuse.com/#feat=download

Does that make sense?

**Comment by jedmarcnocum** [comment]
@monospaced I have a 4.4.4 Android browser version but still the download is not working. :(

**Comment by monospaced** [comment]
Ionic has moved on to Angular now, closing this down as a legacy issue.
