### ISSUE TITLE
String length >62 than not generate qr code.

### ISSUE THREAD

**Issue by altaf933** [monospaced/angular-qrcode#37]
If string character is greater than 62 than it's not able to generate qr code. I can reproduce .
code length overflow. (652>512)

**Comment by monospaced** [comment]
https://github.com/monospaced/angular-qrcode#options

>The amount of data (measured in bits) must be within capacity according to the selected version and error correction level, see http://www.qrcode.com/en/about/version.html.

**Comment by altaf933** [comment]
thanks . Yes i figured out QR code requirement and updated it's version to 5 that match a length of string and issue has resolved. Please close this issue .
