### ISSUE TITLE
need supurt hash or something~when i use the router!

### ISSUE THREAD

**Issue by zhougonglai** [monospaced/angular-qrcode#38]
if i wan't a link like data="http://www.google.com/user/frend#/local/list/1?key=11";
is dosn't work ,but data="http://www.google.com/user/frend" is ok~
can you fix it?

**Comment by zhougonglai** [comment]
sorry,i test in you github.io ,
i use the date like ="https://www.1234567.com/wechat/in#/app/in?frandPhone=15271871141";
that don't creat the canvas```is that data too long ?

**Comment by monospaced** [comment]
This is likely to be issue with data length. Try increasing the version number.

See https://github.com/monospaced/angular-qrcode#options
