### ISSUE TITLE
Cannot handle link with query parameters

### ISSUE THREAD

**Issue by JoeShi** [monospaced/angular-qrcode#41]
I tried

    <qrcode version="4" error-correction-level="H" size="274" data="http://localhost:3000/view?order=111111"></qrcode>

but without the parameter, it works.

    <qrcode version="4" error-correction-level="H" size="274" data="http://localhost:3000/view"></qrcode>

**Comment by monospaced** [comment]
Hi,

Your first example doesn't render because the version is too low to support that amount of data. You need at least version 5.

**Comment by monospaced** [comment]
See https://github.com/monospaced/angular-qrcode#options
