### ISSUE TITLE
Copy QRCode with CTRL+C

### ISSUE THREAD

**Issue by Z3roCoder** [monospaced/angular-qrcode#51]
Hello there! I have a slight issue here.
I am using the plugin in Ionic/Cordova, and am trying to make it Copy-able, but had little success so far.

My code looks something like this:
`<td>
   <qrcode data="http://myQRCode.net" size="150" error-correction-level="M" version="3">
      <canvas width="150" class="qrcode">
      </canvas>
   </qrcode>
</td>`

And I am not able to copy the QRCode at all, neither via selecting it and pressing CTRL-C, nor directly right-clicking on it and saying "Copy"

Am I doing something wrong?

**Comment by monospaced** [comment]
Not through Ionic, but running web version in Chrome on OSX I can:

Right Click > Save Image as

Does that work for you?

**Comment by monospaced** [comment]
Closed due to inactivity
