### ISSUE TITLE
not displaying QR code 

### ISSUE THREAD

**Issue by bhavantejareddy** [monospaced/angular-qrcode#53]
QR code is not displaying the some urls and also i will get value from the server and that is not working at all 

 <qrcode version="1" error-correction-level="L" size="50" data="http://www.ganitix.com/#services" href="www.ganitix.com" ></qrcode>

**Comment by monospaced** [comment]
https://github.com/monospaced/angular-qrcode#important

**Comment by monospaced** [comment]
@bhavantejareddy did that help?

**Comment by monospaced** [comment]
Closed due to inactivity
