### ISSUE TITLE
qrcode is not defined

### ISSUE THREAD

**Issue by brunocascio** [monospaced/angular-qrcode#57]
@monospaced 

`Uncaught ReferenceError: qrcode is not defined     qrcode_UTF8.js on line 59`

My import code:

```
import 'angular-qrcode/node_modules/qrcode-generator/js/qrcode.js';
import 'angular-qrcode/node_modules/qrcode-generator/js/qrcode_UTF8.js';
import 'angular-qrcode/angular-qrcode.js';

angular.module('app', ['monospaced.qrcode'])
```

Template code:

```
<qrcode data="{{vm.code}}"></qrcode>
```

NOTE: I'm using webpack

**Comment by diegofernandesp** [comment]
I'm with the same problem. Any solution?

**Comment by kschima** [comment]
I think you forgot to import:

https://raw.githubusercontent.com/monospaced/bower-qrcode-generator/master/js/qrcode.js

**Comment by brunocascio** [comment]
@kschima, nop I already imported on `import 'angular-qrcode/node_modules/qrcode-generator/js/qrcode.js';` (first line on above comment)

**Comment by burylife** [comment]
add this   
new webpack.ProvidePlugin({
	  
	        , 'qrcode': 'qrcode'
	     
	    }) , may work

**Comment by mgpitt** [comment]
I fixed this issue by adding the following to webpack.config.js 
```
plugins: [ 
      ...
     new webpack.ProvidePlugin({
            qrcode: 'qrcode-generator'
      })
 ]
```

**Comment by monospaced** [comment]
Thanks to all of the contributors on this issue. 🥇 

I have hopefully made some improvements to the installation options.

`angular-qrcode` now exports it's module name.

`qrcode-generator` also now exports it's module - but an extra step may be required to get `qrcode` onto the `window` object. Please see the updated installation section in the README:

https://github.com/monospaced/angular-qrcode#installation
