### ISSUE TITLE
url too long

### ISSUE THREAD

**Issue by SnowMakerDemo** [monospaced/angular-qrcode#65]
─ angular#1.4.9
─ qrcode-generator#0.1.0     url:"https://www.example.com/conat/oautea/author?appid=wxe111111111&redirect_uri=http%3A%2F%2Fwww.example.com%2FWhPortal%2Fdest%2Findex.html%23%2Fsharing-courtesy%3FshareOpenId%3DoodLc1Xb11111110p2VNv2sU%26shareRuleId%3D1002012&response_type=code&scope=snsapi_userinfo&state=12354#wechat_redirect"   this url  is too long   qrcode disappeared ,qrcode-generator   version is lower?

**Comment by monospaced** [comment]
Cannot recreate, this URL works fine in the demo. 

Behaviour was changed in 7.2.0 to automatically select the version
