### ISSUE TITLE
qrcode is not defined

### ISSUE THREAD

**Issue by kalyani-phalke** [monospaced/angular-qrcode#72]
I am getting this error in console and the QR code is not visible in my application. Even it is not visible on http://monospaced.github.io/angular-qrcode demo site

**Comment by rahulbhadhoriya** [comment]
me too

**Comment by monospaced** [comment]
The demo includes Kazuhiko Arase’s [qrcode-generator](https://github.com/kazuhikoarase/qrcode-generator) library on the page via a `script` element, that references a URL on the qrcode-generator GitHub repository. 

__This is a bad idea__, I would not recommend to do this in production code! 

As this is just a link to an asset on another github repository, it is not under control of angular-qrcode, and can change at any time. Which is what just happened :)

I have now updated the demo to use the new url:

````
<script src="//kazuhikoarase.github.io/qrcode-generator/js/demo/assets/qrcode.js"></script>
````

The recommend approach is to install the package via npm (or bower, but this is deeprecated), and then reference the required copy of qrcode-generator /qrcode.js from the installed package.
