### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by clarson** [monospaced/angular-qrcode#77]
Demo at https://github.com/monospaced/angular-qrcode is currently broken.  Appears to be failing to load the below resource.

https://kazuhikoarase.github.io/qrcode-generator/js/demo/assets/qrcode.js

Thanks,
Chuck

**Comment by fffjacquier** [comment]
Need to remove the demo/assets folder from the url
https://kazuhikoarase.github.io/qrcode-generator/js/qrcode.js

**Comment by franconeilglovasa** [comment]
any fix on this one? cant make it work
